version: "3"
services:
  recto:
    build: './recto'
    ports:
      - "3000:3000"
    networks:
      - sinopia
  verso:
    build:
      context: './verso'
    ports:
      - "3001:3001"
    networks:
      - sinopia

networks:
  sinopia:
